### ISSUE TITLE
New Karuta Terminology

### ISSUE THREAD

**Issue by jasmith1113** [karutaproject/karutaproject#1]
We have agreed that there will be new terminology for the items that are currently called portfolios (in Karuta 1.0 to 1.2). The following list is the agreed upon replacement terminology.
1.  Rubric
2.  Reusable (or Portfolio) Components
3.  Portfolio Model
4.  Dashboard Script
5.  Report Script
6.  Batch Script
7.  Portfolios
8.  Projects (admin and designer only)
Number 8 represents new functionality with folders of "portfolios" for each project.

**Comment by olivier-gerbe** [comment]
Done in version 2.0
